# This is a basic workflow to help you get started with Actions

name: Pytest/Behave

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "documentation" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Display testing message
        run: echo Running PyTest

      # Running PyTest
      - name: Runs a basic pytest check
        run: |
          pip install pytest
          pytest test_add.py

      # Running Behave
      - name: Runs a basic behave test
        run: |
          pip install behave
          behave
  behave:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install behave
        run: pip install behave
      - name: Runs a basic behave test
        run: behave
      - name: Runst behave test on test_code
        run: |
          cd testing_code
          behave
